version: '3'

services:
  docker-get-url-hourly-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - URL
      - SESSION_COOKIE
      - SESSION_COOKIE_DELIMITER
    command: crond -f